default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: zoo_dev
test:
  <<: *default
  database: zoo_test

production:
  <<: *default
  database: bold_prod
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>

